add value protection
zehortigoza/aero-optical-flow pull request #19
Opened 2018-02-15 10:17 UTC by ChristophTobler

For time to time the gyro and dt values are way to big. I added a protection against that. You can either merge this PR or https://github.com/intel-aero/aero-optical-flow/pull/16 and then I'll rebase.

2018-02-20 18:53 UTC, zehortigoza requested changes
Please fix the code style and just send the 'add protection against huge gyro/dt values' patch.
@avinash-palleti can pickup your 'CMakeLists: print msg when using FastRTPS' and add to his PR.

2018-02-20 18:53 UTC, zehortigoza commented on src/mainloop.cpp
> +	    dt < max_dt && abs(msg->xgyro) < max_gyro && abs(msg->ygyro) < max_gyro && abs(msg->zgyro) < max_gyro) {
Looks good but the code style is complete messed.

2018-02-20 18:53 UTC, zehortigoza commented on src/mainloop.cpp
> -
remove it

2018-03-02 10:31 UTC, ChristophTobler commented
@zehortigoza done

2018-03-12 17:52 UTC, zehortigoza commented
merged thanks

2018-03-12 17:52 UTC, closed without merging